services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - db_data:/var/lib/mysql

    wordpress:
        image: wordpress:php8.2
        ports:
            - '${WP_PORT}:80'
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - ./themes/ritual_tula:/var/www/html/wp-content/themes/ritual_tula
        depends_on:
            - db

volumes:
    db_data:
