services:
    db:
        image: mysql:8.0
        container_name: wp_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - wordpress-network

    wordpress:
        image: wordpress:latest
        container_name: wp_app
        restart: unless-stopped
        ports:
            - '${WORDPRESS_PORT}:80'
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./wordpress:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - db
        networks:
            - wordpress-network

volumes:
    db_data:

networks:
    wordpress-network:
        driver: bridge
